import Head from 'next/head'
import { Inter } from 'next/font/google'
import CoverImage from '@/components/CoverImage'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <CoverImage
          title='Main Project'
          image='https://res.cloudinary.com/dhbrsb9qd/image/upload/v1678448794/large_home_background_3c5303585a.jpg'
        />
        <section className='flex flex-col md:flex-row justify-between max-w-screen-xl mx-auto py-20 md:py-24 items-center'>
          <div className='md:w-4/12 flex-shrink-0 relative '>
            <CoverImage
              title='profile'
              image='https://res.cloudinary.com/dhbrsb9qd/image/upload/v1678449040/thumbnail_profile_8e0511d7b8.jpg'
            />
          </div>
          <div className='md:w-8/12 mt-16 md:mt-0 md:ml-12 lg:ml-16 md:order-last'>
            <div className='g:py-8 text-center md:text-left'>
              <h2 className='mb-8 text-4xl md:text-5xl font-bold tracking-tighter leading-tight'>
                About me
              </h2>
              <p className='my-5 max-w-[600px] text-neutral-800 dark:text-neutral-200'>
                Lorem Ipsum is simply dummy text of the printing and typesetting
                industry. Lorem Ipsum has been the industrys standard dummy
                text ever since the 1500s
              </p>
              <span className='text-left'>
                <Link href='/about'>Read More</Link>
              </span>
            </div>
          </div>
        </section>
        <section className='flex flex-col md:flex-row justify-between max-w-screen-xl mx-auto py-20 md:py-24 items-center'>
          <div className='md:w-4/12 mt-16 md:mt-0 md:mr-12 lg:mr-16 md:order-firs'>
            <div className='g:py-8 text-center md:text-left'>
              <h2 className='mb-8 text-4xl md:text-5xl font-bold tracking-tighter leading-tight'>
                Projects
              </h2>
              <p className='my-5 max-w-[600px] text-neutral-800 dark:text-neutral-200'>
                Lorem Ipsum is simply dummy text of the printing and typesetting
                industry. Lorem Ipsum has been the industrys standard dummy
                text ever since the 1500s
              </p>
              <span className='text-left'>
                <Link href='/projects'>Read More</Link>
              </span>
            </div>
          </div>
          {/* <div className='md:w-8/12 flex-shrink-0 relative '>
            <EmblaCarousel slides={SLIDES} options={OPTIONS} />
          </div> */}
        </section>
      </main>
    </>
  )
}
